# Generated by Django 5.1.2 on 2024-10-30 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('health_history', models.CharField(max_length=100, null=True)),
                ('prior_treatments', models.CharField(max_length=100, null=True)),
                ('allergies', models.CharField(max_length=100, null=True)),
                ('existing_conditions', models.CharField(max_length=100, null=True)),
                ('family_history', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
